### PR TITLE
Added feature persist anchors to included yaml files

### PR DESCRIPTION
**Pull request by NoahFeinberg**
Hi tanbro, I thought it would be nice if this library also supported anchors when including a yaml file so I wrote this PR. I based code for this update on this stack over flow thread https://stackoverflow.com/questions/44910886/pyyaml-include-file-and-yaml-aliases-anchors-references 

Below is an example for how the new feature works:

## group.yml
```
group
  user:
    name: noah
    team: *team 
  user:
    name: aron
    team *team
```
## devops.yml
```
team: &team devops
devops: !include group.yml
```
## output.yml
```
devops:
  group
    user:
      name: noah
      team: devops 
    user:
      name: aron
      team: devops
```

### CODE REVIEW

**Comment by tanbro** [comment]
@NoahFeinberg Great job!

Will you commit some testcases for anchors?

**Comment by NoahFeinberg** [comment]
sure thing I will work on a PR with some updates

**Comment by NoahFeinberg** [comment]
Sorry haven't found time to write test cases will come back to this when I find some free time

**Comment by tanbro** [comment]
> Is there any documentation on this? I have not been able to reproduce this behavior with persist-anchors=True

Sorry for that the feature does NOT migrate into v2.0 .

**Pull request merged**
