### PR TITLE
Feature/relative includes

### PR DESCRIPTION
**Pull request by JensHeinrich**
Add the option to import relative to the current file to support structures like

```a.yml
test: !include foo/b.yml
```

```foo/b.yml
some: !include bar/c.yml
```

```foo/bar/c.yml
feature: "Feature"
```

### CODE REVIEW

**Comment by tanbro** [comment]
@JensHeinrich thanks for the nice feature.
But the test cases in `tests/test_relative_dir.py` not passed (<https://github.com/tanbro/pyyaml-include/actions/runs/4006591315>)
Would you fix it?

**Comment by JensHeinrich** [comment]
> @JensHeinrich thanks for the nice feature. But the test cases in `tests/test_relative_dir.py` not passed (https://github.com/tanbro/pyyaml-include/actions/runs/4006591315) Would you fix it?

Yes, working on it

**Comment by JensHeinrich** [comment]
> @JensHeinrich thanks for the nice feature. But the test cases in `tests/test_relative_dir.py` not passed (https://github.com/tanbro/pyyaml-include/actions/runs/4006591315) Would you fix it?

So, I just realized I used a python 3.8 feature for the unittests ...
Should I just suppress the tests for the earlier versions or try to work around the feature?

**Comment by idantene** [comment]
This considers a single indirection call, and fails in any other case (that is, the include is now relevant to the top-most yaml file, rather than each file individually). See my comments [here](https://github.com/tanbro/pyyaml-include/issues/23#issuecomment-1411850300).

**Pull request merged**
